[package]
name = "esercizi"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["rogue_lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
rogue_lib = { path = "rogue_lib" }
